---
- hosts: all
  gather_facts: yes

   - name: Users | Create new user
      user: 
        name:{{ lookup('env','USERNAME') }} 
        createhome:yes 
        home:/home/{{ lookup('env','USERNAME') }} 
        generate_ssh_key:yes 
        shell:/bin/bash 
        password:{{ lookup('env','PASS') }}
