---
- name: ansibletest 
  hosts: all
  gather_facts: true
  tasks:
  - name: test
    user: 
      name: test2
      create_home: yes
      home: /home/test2
      generate_ssh_key: yes
      shell: /bin/bash
      password: test2
